<?xml version='1.0' encoding='UTF-8'?><!-- Published by JAX-WS RI (http://jax-ws.java.net). RI's version is Metro/2.3.1-b419 (branches/2.3.1.x-7937; 2014-08-04T08:11:03+0000) JAXWS-RI/2.2.10-b140803.1500 JAXWS-API/2.2.11 JAXB-RI/2.2.10-b140802.1033 JAXB-API/2.2.12-b140109.1041 svn-revision#unknown. --><definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/Web-Services-hw2-Bank/java/bankWSDL" xmlns:ns="http://bank/" name="bankWSDL" targetNamespace="http://bank/">
    <types/>
    <message name="payRequest">
        <part name="personName" type="xsd:string"/>
        <part name="creditCard" type="xsd:string"/>
        <part name="amount" type="xsd:double"/>
    </message>
    <message name="payResponse">
        <part name="return" type="xsd:boolean"/>
    </message>
    <portType name="BankServices">
        <operation name="pay">
            <input name="input1" message="ns:payRequest"/>
            <output name="output1" message="ns:payResponse"/>
        </operation>
    </portType>
</definitions>